export const TYPES = {
    GET_FILES_USER: 'GET_FILES_USER',
    RESET: 'RESET',
    REFRESH_GRID_LIST: 'REFRESH_GRID_LIST',
    SET_AVATAR_USERNAME_OCCUPATION: 'SET_AVATAR_USERNAME_OCCUPATION',
    SET_EMAIL_OR_PASSWORD: 'SET_EMAIL_OR_PASSWORD',
    GRID_VIEW: 'GRID_VIEW',
    LIST_VIEW: 'LIST_VIEW',
    NEW_FILES_FIRST: 'NEW_FILES_FIRST',
    OLD_FILES_FIRST: 'OLD_FILES_FIRST',
  }