export const TYPES = {
    GET_FILES_USER: 'GET_FILES_USER',
    NEW_FILE_UPLOADED: 'NEW_FILE_UPLOADED',
    RESET: 'RESET',
    SET_AVATAR_USERNAME_OCCUPATION: 'SET_AVATAR_USERNAME_OCCUPATION',
    SET_EMAIL_OR_PASSWORD: 'SET_EMAIL_OR_PASSWORD',
    GRID_VIEW: 'GRID_VIEW',
    LIST_VIEW: 'LIST_VIEW',
    NEW_FILES_FIRST: 'NEW_FILES_FIRST',
    OLD_FILES_FIRST: 'OLD_FILES_FIRST',
    ALL_FILES: 'ALL_FILES',
    ONLY_DOCUMENTS: 'ONLY_DOCUMENTS',
    ONLY_MULTIMEDIA: 'ONLY_MULTIMEDIA',
    COUNTDOWN: 'COUNTDOWN',
    RENAME_FILE: 'RENAME_FILE',
    DLT_FILE: 'DLT_FILE'
  }